#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# Copyright 2025 Peter Tribble
#
# build jumble
#

PATH=/usr/jdk/instances/jdk1.8.0/bin:$PATH
export PATH

#
# new PMD version has categories only
#
PMDCATRULES="security bestpractices"
PMDCACHE="${HOME}/.pmd/cache.jumble"

case $1 in
clean)
	rm -f $(find uk/co -type f -name '*.class')
	rm -f $(find . -type f -name '*~')
	rm -fr javadoc
	exit 0
	;;
pmd|-pmd)
	RULESETS=""
	for RULE in $PMDCATRULES "$@"
	do
	    RULESETS="${RULESETS},category/java/${RULE}.xml"
	done
	RULESETS=${RULESETS/,/}
	if [ ! -d "${HOME}/.pmd" ]; then
	    mkdir -p "${HOME}/.pmd"
	fi
	pmd check --cache "${PMDCACHE}" -d uk -R $RULESETS --use-version java-1.8 2>/dev/null
	exit 0
	;;
javadoc|-javadoc)
    rm -fr javadoc
    mkdir javadoc
    javadoc -d javadoc uk.co.petertribble.jumble
    exit 0
    ;;
esac

javac -Xlint uk/co/petertribble/jumble/*.java

jar cf jumble.jar $(find uk/co/petertribble/jumble -name '*.class')
