#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# Copyright 2025 Peter Tribble
#
# build jumble
#

PATH=/usr/jdk/instances/jdk11/bin:$PATH
export PATH

#
# new PMD version 7 only has categories, configured in pmd-ruleset.xml
#
PMDRULES="./pmd-ruleset.xml"
PMDCACHE="${HOME}/.pmd/cache.jumble"

case $1 in
clean)
	rm -f $(find uk/co -type f -name '*.class')
	rm -f $(find . -type f -name '*~')
	rm -fr javadoc
	exit 0
	;;
pmd)
	if [ ! -d "${HOME}/.pmd" ]; then
	    mkdir -p "${HOME}/.pmd"
	fi
	pmd check --cache "${PMDCACHE}" -d uk -R "${PMDRULES}" --use-version java-11 2>/dev/null
	exit 0
	;;
spotbugs)
	#
	# spotbugs works on the class files, so those need to be available
	#
	javac -Xlint uk/co/petertribble/jumble/*.java
	spotbugs -auxclasspath jumble.jar uk
	rm -f $(find uk/co/petertribble/jumble -type f -name '*.class')
	exit 0
	;;
javadoc)
    rm -fr javadoc
    mkdir javadoc
    javadoc -Xdoclint:all -d javadoc uk.co.petertribble.jumble
    exit 0
    ;;
esac

javac -Xlint uk/co/petertribble/jumble/*.java

jar cf jumble.jar $(find uk/co/petertribble/jumble -name '*.class')

rm -f $(find uk/co/petertribble/jumble -type f -name '*.class')
