#!/bin/sh
#
# build jumble
#

XFLAGS="-Xlint -Xlint:-serial"
#XFLAGS=""

#
# new PMD version has rulesets
#
PMDRULES="imports typeresolution clone finalizers sunsecure unusedcode braces migrating strictexception unnecessary"
PMDCATRULES="security bestpractices"
PMDCACHE="${HOME}/.pmd/cache.jumble"

case $1 in
clean)
	rm -f `find uk/co -type f -name '*.class'`
	rm -f `find . -type f -name '*~'`
	rm -fr javadoc
	exit 0
	;;
pmd|-pmd)
	RULESETS=""
	for RULE in $PMDRULES
	do
	    RULESETS="${RULESETS},rulesets/java/${RULE}.xml"
	done
	for RULE in $PMDCATRULES
	do
	    RULESETS="${RULESETS},category/java/${RULE}.xml"
	done
	RULESETS=`echo $RULESETS|sed s:,::`
	if [ ! -d ${HOME}/.pmd ]; then
	    mkdir -p ${HOME}/.pmd
	fi
	pmd check --cache ${PMDCACHE} -d uk -R $RULESETS --use-version java-1.8 --aux-classpath `echo lib/java/* | sed 's= =:=g'` 2>/dev/null
	exit 0
	;;
doc|-doc)
    rm -fr javadoc
    mkdir javadoc
    javadoc -d javadoc uk.co.petertribble.jumble
    ;;
esac

if [ -x /opt/onbld/bin/jstyle ]; then
    /opt/onbld/bin/jstyle `find uk/co/petertribble/jumble -name '*.java'`
fi

javac ${XFLAGS} uk/co/petertribble/jumble/*.java

jar cf jumble.jar `find uk/co/petertribble/jumble -name '*.class'`
